--- 
apiVersion: v1
kind: ConfigMap 
metadata:
  name: data-vol 
  namespace: default
data:
  index.html: |
    <h1>hello, world</h1>
    <h2>This is my deployment</h2>
  about.html: |
    <h1>magical me!</h1>

---
apiVersion: v1
kind: Secret 
metadata:
  name: secret-vol 
  namespace: default
data:
  token: aHVzaCBodXNo